-- Development seed data for posts table
-- WARNING: This will clear all existing posts data!

-- Clear existing data (dev only!)
TRUNCATE TABLE posts CASCADE;

-- Insert sample meme posts (100 total)
INSERT INTO posts (id, title, image_url, description, categories) VALUES
    ('post-1', 'Distracted Boyfriend', 'https://i.imgflip.com/1ur9b0.jpg', 'The classic distracted boyfriend meme', ARRAY['classic', 'relationship', 'funny']),
    ('post-2', 'Drake Hotline Bling', 'https://i.imgflip.com/30b1gx.jpg', 'Drake approving and disapproving', ARRAY['drake', 'reaction', 'classic']),
    ('post-3', 'Two Buttons', 'https://i.imgflip.com/1g8my4.jpg', 'Daily struggle choosing between two options', ARRAY['choices', 'struggle', 'relatable']),
    ('post-4', 'Change My Mind', 'https://i.imgflip.com/24y43o.jpg', 'Steven Crowder change my mind meme', ARRAY['debate', 'opinion', 'crowder']),
    ('post-5', 'Is This A Pigeon?', 'https://i.imgflip.com/1o00in.jpg', 'Anime butterfly meme about misidentification', ARRAY['anime', 'confusion', 'classic']),
    ('post-6', 'Success Kid', 'https://i.imgflip.com/1bhk.jpg', 'Determined baby fist pump', ARRAY['success', 'victory', 'classic']),
    ('post-7', 'Expanding Brain', 'https://i.imgflip.com/1jwhww.jpg', 'Increasingly enlightened ideas', ARRAY['brain', 'evolution', 'smart']),
    ('post-8', 'Woman Yelling at Cat', 'https://i.imgflip.com/345v97.jpg', 'Woman yelling at confused cat at dinner table', ARRAY['cat', 'yelling', 'confusion']),
    ('post-9', 'Bernie Sanders Once Again Asking', 'https://i.imgflip.com/3oevdk.jpg', 'Bernie Sanders asking for support', ARRAY['bernie', 'politics', 'asking']),
    ('post-10', 'This Is Fine', 'https://i.imgflip.com/wxica.jpg', 'Dog in burning room saying this is fine', ARRAY['fire', 'calm', 'chaos']),
    ('post-11', 'Roll Safe', 'https://i.imgflip.com/1h7in3.jpg', 'Can''t fail if you don''t try', ARRAY['smart', 'thinking', 'logic']),
    ('post-12', 'Surprised Pikachu', 'https://i.imgflip.com/2kbn1e.jpg', 'Unexpected consequences', ARRAY['pikachu', 'pokemon', 'surprise']),
    ('post-13', 'Ancient Aliens', 'https://i.imgflip.com/26am.jpg', 'Giorgio Tsoukalos aliens guy', ARRAY['aliens', 'conspiracy', 'history']),
    ('post-14', 'Batman Slapping Robin', 'https://i.imgflip.com/9ehk.jpg', 'Batman shutting down bad ideas', ARRAY['batman', 'slap', 'comics']),
    ('post-15', 'Mocking SpongeBob', 'https://i.imgflip.com/1otk96.jpg', 'Sarcastic chicken SpongeBob', ARRAY['spongebob', 'mocking', 'sarcasm']),
    ('post-16', 'Left Exit 12 Off Ramp', 'https://i.imgflip.com/22bdq6.jpg', 'Taking the wrong exit decision', ARRAY['exit', 'decision', 'car']),
    ('post-17', 'Running Away Balloon', 'https://i.imgflip.com/261o3j.jpg', 'Chasing after the wrong thing', ARRAY['balloon', 'priorities', 'chase']),
    ('post-18', 'Monkey Puppet', 'https://i.imgflip.com/3lmzyx.jpg', 'Awkward side-eye puppet', ARRAY['puppet', 'awkward', 'sideeye']),
    ('post-19', 'Tuxedo Winnie The Pooh', 'https://i.imgflip.com/2ybua0.jpg', 'Fancy vs regular preferences', ARRAY['pooh', 'fancy', 'classy']),
    ('post-20', 'Am I The Only One', 'https://i.imgflip.com/cq1q.jpg', 'Walter from Big Lebowski questioning', ARRAY['lebowski', 'question', 'wondering']),
    ('post-21', 'Spider-Man Pointing', 'https://i.imgflip.com/2izvfl.jpg', 'Two Spider-Men pointing at each other', ARRAY['spiderman', 'pointing', 'duplicate']),
    ('post-22', 'Disaster Girl', 'https://i.imgflip.com/23ls.jpg', 'Little girl smiling at burning house', ARRAY['fire', 'evil', 'chaos']),
    ('post-23', 'Waiting Skeleton', 'https://i.imgflip.com/2fm6x.jpg', 'Skeleton waiting forever', ARRAY['waiting', 'skeleton', 'forever']),
    ('post-24', 'Homer Simpson Backing Into Bushes', 'https://i.imgflip.com/jc2.jpg', 'Homer disappearing into hedge', ARRAY['homer', 'simpsons', 'retreat']),
    ('post-25', 'Blank Nut Button', 'https://i.imgflip.com/1yxkcp.jpg', 'Pressing the button enthusiastically', ARRAY['button', 'press', 'enthusiasm']),
    ('post-26', 'Boardroom Meeting Suggestion', 'https://i.imgflip.com/m78d.jpg', 'Getting thrown out window for suggestion', ARRAY['meeting', 'window', 'corporate']),
    ('post-27', 'They''re The Same Picture', 'https://i.imgflip.com/1c1uej.jpg', 'Pam from The Office seeing no difference', ARRAY['office', 'same', 'nodifference']),
    ('post-28', 'Who Would Win?', 'https://i.imgflip.com/1il1qy.jpg', 'Comparing two unequal opponents', ARRAY['versus', 'comparison', 'battle']),
    ('post-29', 'Panik Kalm Panik', 'https://i.imgflip.com/3kkzby.jpg', 'Panic calm panic sequence', ARRAY['panic', 'calm', 'anxiety']),
    ('post-30', 'Gru''s Plan', 'https://i.imgflip.com/26jy7v.jpg', 'Despicable Me plan goes wrong', ARRAY['gru', 'plan', 'despicableme']),
    ('post-31', 'Star Wars Yoda', 'https://i.imgflip.com/29gymp.jpg', 'Yoda wisdom', ARRAY['yoda', 'starwars', 'wisdom']),
    ('post-32', 'Futurama Fry', 'https://i.imgflip.com/1bgw.jpg', 'Not sure if...', ARRAY['fry', 'futurama', 'suspicious']),
    ('post-33', 'X All The Y', 'https://i.imgflip.com/1bh.jpg', 'Do all the things!', ARRAY['all', 'everything', 'enthusiasm']),
    ('post-34', 'Disaster Girl', 'https://i.imgflip.com/grr.jpg', 'Evil toddler planning', ARRAY['toddler', 'evil', 'planning']),
    ('post-35', 'Inhaling Seagull', 'https://i.imgflip.com/3uen1i.jpg', 'Seagull screaming intensely', ARRAY['seagull', 'scream', 'bird']),
    ('post-36', 'Trade Offer', 'https://i.imgflip.com/54hjww.jpg', 'I receive, you receive', ARRAY['trade', 'deal', 'negotiation']),
    ('post-37', 'Always Has Been', 'https://i.imgflip.com/3cd2fm.jpg', 'Astronaut betrayal in space', ARRAY['astronaut', 'space', 'betrayal']),
    ('post-38', 'Buff Doge vs Cheems', 'https://i.imgflip.com/43a45p.jpg', 'Strong doge vs weak doge comparison', ARRAY['doge', 'comparison', 'strong']),
    ('post-39', 'Stonks', 'https://i.imgflip.com/2nqnw7.jpg', 'Financial meme man', ARRAY['stonks', 'stocks', 'finance']),
    ('post-40', 'Clown Applying Makeup', 'https://i.imgflip.com/38el31.jpg', 'Gradually becoming a clown', ARRAY['clown', 'makeup', 'escalation']),
    ('post-41', 'Math Lady', 'https://i.imgflip.com/1wz1t.jpg', 'Confused math calculations', ARRAY['math', 'confused', 'calculations']),
    ('post-42', 'Laughing Leo', 'https://i.imgflip.com/261huq.jpg', 'Leonardo DiCaprio laughing with drink', ARRAY['leo', 'dicaprio', 'laughing']),
    ('post-43', 'Doge', 'https://i.imgflip.com/4t0m5.jpg', 'Much wow, such meme', ARRAY['doge', 'shiba', 'wow']),
    ('post-44', 'Hide the Pain Harold', 'https://i.imgflip.com/gk5el.jpg', 'Hiding internal pain with smile', ARRAY['harold', 'pain', 'smile']),
    ('post-45', 'First Time?', 'https://i.imgflip.com/2zm2mo.jpg', 'Gallows hanging meme', ARRAY['firsttime', 'experienced', 'veteran']),
    ('post-46', 'Bike Fall', 'https://i.imgflip.com/1b42wl.jpg', 'Putting stick in bike wheel', ARRAY['bike', 'fall', 'selfsabotage']),
    ('post-47', 'Drake Post Malone', 'https://i.imgflip.com/30cz64.jpg', 'Post Malone version of Drake meme', ARRAY['postmalone', 'drake', 'rapper']),
    ('post-48', 'Marked Safe From', 'https://i.imgflip.com/43jdn4.jpg', 'Facebook safety check parody', ARRAY['safe', 'facebook', 'announcement']),
    ('post-49', 'Anakin Padme', 'https://i.imgflip.com/3gqzd0.jpg', 'Anakin and Padme conversation', ARRAY['starwars', 'anakin', 'padme']),
    ('post-50', 'Sad Pablo Escobar', 'https://i.imgflip.com/1c1uej.jpg', 'Pablo sitting alone', ARRAY['narcos', 'pablo', 'sad']),
    ('post-51', 'Guess I''ll Die', 'https://i.imgflip.com/2cp1.jpg', 'Old man accepting fate', ARRAY['die', 'accept', 'shrug']),
    ('post-52', 'Flex Tape', 'https://i.imgflip.com/2wifvo.jpg', 'Phil Swift and flex tape', ARRAY['flextape', 'phil', 'repair']),
    ('post-53', 'Upgrade', 'https://i.imgflip.com/22npc9.jpg', 'Choosing the better option', ARRAY['upgrade', 'choice', 'better']),
    ('post-54', 'Shut Up And Take My Money', 'https://i.imgflip.com/3si4.jpg', 'Fry throwing money', ARRAY['money', 'throw', 'futurama']),
    ('post-55', 'Grandma Finds The Internet', 'https://i.imgflip.com/1bhk.jpg', 'Elderly woman discovering internet', ARRAY['grandma', 'internet', 'discovery']),
    ('post-56', 'Skeleton Waiting', 'https://i.imgflip.com/2fm6x.jpg', 'Still waiting...', ARRAY['waiting', 'patience', 'long']),
    ('post-57', 'Captain America Elevator', 'https://i.imgflip.com/30b1gx.jpg', 'I can do this all day', ARRAY['captainamerica', 'elevator', 'marvel']),
    ('post-58', 'Elmo Fire', 'https://i.imgflip.com/2d3al6.jpg', 'Elmo in front of fire', ARRAY['elmo', 'fire', 'sesamestreet']),
    ('post-59', 'Sleeping Shaq', 'https://i.imgflip.com/3bd2iw.jpg', 'Shaq sleeping vs awake', ARRAY['shaq', 'sleep', 'awake']),
    ('post-60', 'Oprah You Get A Car', 'https://i.imgflip.com/gtj5t.jpg', 'You get a car!', ARRAY['oprah', 'car', 'gift']),
    ('post-61', 'Types of Headaches', 'https://i.imgflip.com/3si4.jpg', 'Different levels of headache', ARRAY['headache', 'pain', 'levels']),
    ('post-62', 'Tom Cruise Laugh', 'https://i.imgflip.com/2d3al6.jpg', 'Tom Cruise laughing', ARRAY['tomcruise', 'laugh', 'interview']),
    ('post-63', 'Beans', 'https://i.imgflip.com/3bd2iw.jpg', 'Random beans meme', ARRAY['beans', 'random', 'food']),
    ('post-64', 'Ah Yes Enslaved', 'https://i.imgflip.com/3gqzd0.jpg', 'Ah yes, enslaved [blank]', ARRAY['enslaved', 'science', 'logic']),
    ('post-65', 'Area 51', 'https://i.imgflip.com/30cz64.jpg', 'Storm Area 51 meme', ARRAY['area51', 'aliens', 'raid']),
    ('post-66', 'You Guys Are Getting Paid?', 'https://i.imgflip.com/1wz1t.jpg', 'We''re The Millers scene', ARRAY['paid', 'surprise', 'money']),
    ('post-67', 'No I Don''t Think I Will', 'https://i.imgflip.com/30b1gx.jpg', 'Old Captain America', ARRAY['captainamerica', 'refuse', 'no']),
    ('post-68', 'Professional Have Standards', 'https://i.imgflip.com/2d3al6.jpg', 'TF2 Sniper quote', ARRAY['tf2', 'sniper', 'standards']),
    ('post-69', 'Observe', 'https://i.imgflip.com/3bd2iw.jpg', 'Megamind observe meme', ARRAY['megamind', 'observe', 'watch']),
    ('post-70', 'Me And The Boys', 'https://i.imgflip.com/3gqzd0.jpg', 'Spider-Man villains group', ARRAY['boys', 'group', 'spiderman']),
    ('post-71', 'Bonjour Bear', 'https://i.imgflip.com/30cz64.jpg', 'Bear saying hello', ARRAY['bear', 'bonjour', 'hello']),
    ('post-72', 'Mom Come Pick Me Up', 'https://i.imgflip.com/1wz1t.jpg', 'I''m scared', ARRAY['mom', 'scared', 'pickup']),
    ('post-73', 'Ight Imma Head Out', 'https://i.imgflip.com/30b1gx.jpg', 'SpongeBob leaving', ARRAY['spongebob', 'leave', 'exit']),
    ('post-74', 'How Do You Do Fellow Kids', 'https://i.imgflip.com/2d3al6.jpg', 'Steve Buscemi undercover', ARRAY['fellowkids', 'buscemi', 'cool']),
    ('post-75', 'Why Are You Running', 'https://i.imgflip.com/3bd2iw.jpg', 'Confused running', ARRAY['running', 'why', 'chase']),
    ('post-76', 'Patrick Not My Wallet', 'https://i.imgflip.com/3gqzd0.jpg', 'Is this your wallet?', ARRAY['patrick', 'wallet', 'spongebob']),
    ('post-77', 'Coffin Dance', 'https://i.imgflip.com/30cz64.jpg', 'Dancing pallbearers', ARRAY['coffin', 'dance', 'funeral']),
    ('post-78', 'Vibing Cat', 'https://i.imgflip.com/1wz1t.jpg', 'Cat vibing to music', ARRAY['cat', 'vibe', 'music']),
    ('post-79', 'Juan Horse', 'https://i.imgflip.com/30b1gx.jpg', 'Horse on balcony', ARRAY['juan', 'horse', 'balcony']),
    ('post-80', 'Pizza Time', 'https://i.imgflip.com/2d3al6.jpg', 'Tobey Maguire pizza delivery', ARRAY['pizza', 'spiderman', 'time']),
    ('post-81', 'Parkour', 'https://i.imgflip.com/3bd2iw.jpg', 'The Office parkour', ARRAY['parkour', 'office', 'jump']),
    ('post-82', 'Corporate Needs You', 'https://i.imgflip.com/3gqzd0.jpg', 'Find the difference', ARRAY['corporate', 'same', 'office']),
    ('post-83', 'Unsettled Tom', 'https://i.imgflip.com/30cz64.jpg', 'Tom and Jerry concerned face', ARRAY['tom', 'unsettled', 'concern']),
    ('post-84', 'Da Vinky', 'https://i.imgflip.com/1wz1t.jpg', 'Da Vinci?', ARRAY['davinky', 'davinci', 'art']),
    ('post-85', 'BONK', 'https://i.imgflip.com/30b1gx.jpg', 'Go to horny jail', ARRAY['bonk', 'horny', 'jail']),
    ('post-86', 'Literally Me', 'https://i.imgflip.com/2d3al6.jpg', 'Relatable moment', ARRAY['literally', 'me', 'relatable']),
    ('post-87', 'Years of Academy Training Wasted', 'https://i.imgflip.com/3bd2iw.jpg', 'Buzz Lightyear disappointed', ARRAY['wasted', 'training', 'toystory']),
    ('post-88', 'Bro Explaining', 'https://i.imgflip.com/3gqzd0.jpg', 'Explaining with hands', ARRAY['explaining', 'hands', 'bro']),
    ('post-89', 'Bernie Mittens', 'https://i.imgflip.com/30cz64.jpg', 'Bernie Sanders with mittens', ARRAY['bernie', 'mittens', 'inauguration']),
    ('post-90', 'It Is Wednesday My Dudes', 'https://i.imgflip.com/1wz1t.jpg', 'Frog announcing Wednesday', ARRAY['wednesday', 'frog', 'dudes']),
    ('post-91', 'Big Brain Time', 'https://i.imgflip.com/30b1gx.jpg', 'It''s big brain time', ARRAY['bigbrain', 'smart', 'genius']),
    ('post-92', 'Ah Shit Here We Go Again', 'https://i.imgflip.com/2d3al6.jpg', 'GTA San Andreas CJ', ARRAY['gta', 'again', 'repeat']),
    ('post-93', 'Chuckles I''m In Danger', 'https://i.imgflip.com/3bd2iw.jpg', 'Ralph Wiggum in danger', ARRAY['danger', 'simpsons', 'ralph']),
    ('post-94', 'Modern Problems Require Modern Solutions', 'https://i.imgflip.com/3gqzd0.jpg', 'Dave Chappelle tapping head', ARRAY['modern', 'solutions', 'smart']),
    ('post-95', 'Understandable Have a Nice Day', 'https://i.imgflip.com/30cz64.jpg', 'Understandable have a great day', ARRAY['understandable', 'nice', 'day']),
    ('post-96', 'They Had Us In The First Half', 'https://i.imgflip.com/1wz1t.jpg', 'Not gonna lie', ARRAY['firsthalf', 'twist', 'surprise']),
    ('post-97', 'Invest', 'https://i.imgflip.com/30b1gx.jpg', 'Meme economy invest', ARRAY['invest', 'stonks', 'economy']),
    ('post-98', 'Professionals Have Standards', 'https://i.imgflip.com/2d3al6.jpg', 'Be polite, be efficient', ARRAY['professional', 'standards', 'quality']),
    ('post-99', 'You Dense', 'https://i.imgflip.com/3bd2iw.jpg', 'You dense cabbage', ARRAY['dense', 'insult', 'gordon']),
    ('post-100', 'This Is Brilliant But I Like This', 'https://i.imgflip.com/3gqzd0.jpg', 'Jeremy Clarkson comparison', ARRAY['brilliant', 'prefer', 'topgear']);

-- Display success message
SELECT COUNT(*) as total_posts FROM posts;
